name: Build

on: 
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifact-name: elevblender
            asset-name: elevblender-macos-${{ github.ref }}
          - os: ubuntu-latest
            artifact-name: elevblender
            asset-name: elevblender-ubuntu-${{ github.ref }}
          - os: windows-latest
            artifact-name: elevblender.exe
            asset-name: elevblender-windows-${{ github.ref }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
        working-directory: app

      - name: Build with pyinstaller
        run: pyinstaller -w -y --onefile --name=${{ matrix.artifact_name }} app.py
        working-directory: app

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
