name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries
    if: startsWith(github.ref, 'refs/tags/')

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
        working-directory: app

      - name: Build with pyinstaller
        run: pyinstaller -w --onefile --name=elevblender-${{ matrix.os }} app.py
        working-directory: app

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app/dist/elevblender-${{ matrix.os }}*
          if-no-files-found: error

  Release:
    name: Make release
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      actions: read
      contents: write
    
    runs-on: ubuntu-latest
    steps:
    - name: Wait for Build
      uses: yogeshlonkar/wait-for-jobs@v0.1.4
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        ignore-skipped: 'false'
        jobs: 'latest)'
        suffix: 'true'
    - name: Update release version
      run: echo ${{ github.sha }} > release.txt
    - name: Create release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          release.txt
          app/dist/elevblender-macos-latest*
          app/dist/elevblender-windows-latest*
          app/dist/elevblender-ubuntu-latest*