name: Build

on:
  release: 
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
        working-directory: app

      - name: Build with pyinstaller
        run: pyinstaller -w --onefile --name=elevblender-${{ matrix.os }} app.py
        working-directory: app

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: dist/elevblender-${{ matrix.os }}*
          if-no-files-found: error