name: Build

on:
  release:
    [published]

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller 
        # pytest
          pip install -r requirements.txt
      # - name: Test with pytest
      #   run: pytest

      - name: Build with pyinstaller
        run: pyinstaller -w --onefile --name=elevblender-${{ matrix.os }} main.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app/dist/elevblender-${{ matrix.os }}*
          if-no-files-found: error